language: ruby
rvm:
  - 2.2.3
addons:
  sauce_connect: true
  postgresql: "9.4"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake teaspoon
  - bundle exec rake spec
before_script:
  - psql -c 'create database pa_website_test_db;' -U postgres
  - bundle exec rake assets:precompile
before_install:
  - gem install bundler -v '= 1.10.6'

